import type { ServiceSlug } from './services'

export type ProjectSpan =
  | 'hero'
  | 'landscape'
  | 'third'
  | 'tall'
  | 'wide'
  | 'splitWide'
  | 'splitNarrow'
  | 'half'
  | 'band'

export type ProjectModule =
  | {
      type: 'image'
      src: string
      width: number
      height: number
      alt?: string
      fullBleed?: boolean
    }
  | {
      type: 'text'
      text: string
      align?: 'center'
    }
  | {
      type: 'youtube'
      id: string
    }
  | {
      type: 'vimeo'
      id: string
    }

export type ProjectRecord = {
  slug: string
  name: string
  service: ServiceSlug
  cover: string
  width: number
  height: number
  span: ProjectSpan
  featured: boolean
  behanceId: number
  motionSrc?: string
  sourceUrl?: string
  publishedOn?: number
  description?: string
  modules?: readonly ProjectModule[]
}

/**
 * Public projects from https://www.behance.net/Fouad-Mazid
 * Generated by scripts/fetch-behance-projects.mjs — do not edit by hand.
 */
export const projects: readonly ProjectRecord[] = [
  {
    slug: "whipped-cream-sona",
    name: "Whipped Cream (Sona)",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/5fa05d51947609.Y3JvcCwxMDgyLDg0NywwLDIwNQ.jpg",
    width: 808,
    height: 632,
    span: "hero",
    featured: true,
    behanceId: 51947609,
    sourceUrl: "https://www.behance.net/gallery/51947609/Whipped-Cream-%28Sona%29",
    publishedOn: 1493140093,
    description: "This product has been designed for a food company based in Turkey.\nWe put together each flavor with what is suitable for it.",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/586e8b51947609.58ff763e89d45.jpg",
            "width": 1920,
            "height": 1082,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b18b6c51947609.58ff763e8a1d5.jpg",
            "width": 1920,
            "height": 1082,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/42154351947609.58ff7feadf9a7.jpg",
            "width": 1920,
            "height": 1082,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/77a79351947609.58ff7feadfeb2.jpg",
            "width": 1920,
            "height": 1082,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/5c96e451947609.58ff85d8afdd5.jpg",
            "width": 940,
            "height": 675
        },
        {
            "type": "youtube",
            "id": "ZXQi9PKpt-g"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/f0e55051947609.58ff7feadf4aa.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "dominar-nuts",
    name: "Dominar Nuts",
    service: "logo-design-visual-identity",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/28327837236617.Y3JvcCw0MDQsMzE2LDAsNw.jpg",
    width: 404,
    height: 316,
    span: "landscape",
    featured: true,
    behanceId: 37236617,
    sourceUrl: "https://www.behance.net/gallery/37236617/Dominar-Nuts",
    publishedOn: 1463408509,
    description: "Dominar Nuts ...",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/4955b537236617.5739d69a7e455.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/0df5bd37236617.5739d69a7e996.jpg",
            "width": 431,
            "height": 432
        }
    ],
  },
  {
    slug: "hawraa-nuts",
    name: "Hawraa Nuts",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/0df3e837235283.Y3JvcCw1NzQsNDQ5LDQ5LDA.jpg",
    width: 404,
    height: 316,
    span: "landscape",
    featured: true,
    behanceId: 37235283,
    sourceUrl: "https://www.behance.net/gallery/37235283/Hawraa-Nuts",
    publishedOn: 1463406655,
    description: "Advertising for nuts company",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/17fe5a37235283.5739cf18b4ef2.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b3b34c37235283.587e4b02b3eb6.jpg",
            "width": 430,
            "height": 248
        }
    ],
  },
  {
    slug: "character-design-sunflower-seeds",
    name: "Character Design ( Sunflower Seeds)",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/087a4854481719.Y3JvcCw4NTIsNjY2LDAsMjI5.jpg",
    width: 808,
    height: 632,
    span: "third",
    featured: true,
    behanceId: 54481719,
    sourceUrl: "https://www.behance.net/gallery/54481719/Character-Design-%28-Sunflower-Seeds%29",
    publishedOn: 1499686361,
    description: "We Designed this character for a Food Product (sunflower Seeds)",
    modules: [
        {
            "type": "text",
            "text": "This is a character that We had Designed for a client to Use on a Food Product.",
            "align": "center"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/c3878954481719.595d24fc1252d.jpg",
            "width": 850,
            "height": 993
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b575ed54481719.595d24fc13055.jpg",
            "width": 850,
            "height": 993
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/be856d54481719.595d24fc1228f.jpg",
            "width": 850,
            "height": 993
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/8c169954481719.595d24fc127c3.jpg",
            "width": 850,
            "height": 993
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/342c7b54481719.595d24fc12c96.jpg",
            "width": 850,
            "height": 993
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/1e9d7e54481719.595d24fc11fc1.jpg",
            "width": 850,
            "height": 567
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/7e4a1254481719.595d24fc11ab0.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "restaurant-photos",
    name: "Restaurant Photos",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/a3cc8e42149633.Y3JvcCw2NDYsNTA2LDU3LDA.jpg",
    width: 404,
    height: 316,
    span: "third",
    featured: true,
    behanceId: 42149633,
    sourceUrl: "https://www.behance.net/gallery/42149633/Restaurant-Photos",
    publishedOn: 1472385227,
    description: "صور مأكولات",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/a74d5642149633.57c2c95979897.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/11012442149633.57c2c95979f39.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/16b7f142149633.57c2c9597b97e.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/98474c42149633.57c2c9597d23d.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/ab1b0342149633.57c2c9597e9d7.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/0175df42149633.57c2c959803d3.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/07012a42149633.57c2c95982334.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/5a5cd742149633.57c2c95982a38.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/a0ea1342149633.57c2c959830b3.jpg",
            "width": 986,
            "height": 652
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b5cde042149633.57c2c95985106.jpg",
            "width": 653,
            "height": 985
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/392eec42149633.57c2c95986b56.jpg",
            "width": 653,
            "height": 985
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/ff65fb42149633.57c2c95988724.jpg",
            "width": 652,
            "height": 698
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/fc2d9642149633.57c2c95988d83.jpg",
            "width": 758,
            "height": 672
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/e7e47d42149633.57c2c9598961e.jpg",
            "width": 653,
            "height": 985
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/19c37c42149633.57c2c9598b4c3.jpg",
            "width": 653,
            "height": 985
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/37124b42149633.57c2c9598e138.jpg",
            "width": 1072,
            "height": 1101
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/f813fd42149633.57c2d0b87337e.png",
            "width": 477,
            "height": 313
        }
    ],
  },
  {
    slug: "candy-hospitality",
    name: "Candy hospitality",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/11084f47801087.Y3JvcCwzODI2LDI5OTQsNjMyLDQ3.jpg",
    width: 808,
    height: 632,
    span: "third",
    featured: true,
    behanceId: 47801087,
    sourceUrl: "https://www.behance.net/gallery/47801087/Candy-hospitality",
    publishedOn: 1485165823,
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/f99edc47801087.5885d1610a8a8.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b8e41a47801087.5885d1610ae10.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/dc770947801087.5885d1610b5dd.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b4462d47801087.5885d1610bcc7.jpg",
            "width": 1062,
            "height": 713
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/adbba747801087.5885d1610c39e.jpg",
            "width": 783,
            "height": 1184
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/c5d25a47801087.5885d1610ca83.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/6a63e347801087.5885d1610d117.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/bf0e7647801087.5885d1610d7bb.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/7b673847801087.5885d1610df2b.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/546e0747801087.5885d1610e60c.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/f0eabd47801087.5885d1610ece8.jpg",
            "width": 1183,
            "height": 783
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/20cbd247801087.5885d1610f3be.jpg",
            "width": 1091,
            "height": 724
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/4fe0ae47801087.5885d1610fae1.jpg",
            "width": 960,
            "height": 834
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/bbbd1b47801087.5885d161100eb.jpg",
            "width": 960,
            "height": 834
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/a29c1e47801087.5885d161107f4.jpg",
            "width": 960,
            "height": 834
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/e4d71447801087.5885d16110eae.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "nuts",
    name: "Nuts",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/8453a935220407.Y3JvcCw4MTMsNjM3LDI4OSww.jpg",
    width: 808,
    height: 632,
    span: "tall",
    featured: true,
    behanceId: 35220407,
    sourceUrl: "https://www.behance.net/gallery/35220407/Nuts",
    publishedOn: 1458482758,
    description: "....",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/11ad4335220407.56eeae44e3f90.jpg",
            "width": 4592,
            "height": 2296
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/f945d935220407.56eeae44e47af.jpg",
            "width": 3680,
            "height": 1840
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/ce97cf35220407.56eeae44e4f28.jpg",
            "width": 4592,
            "height": 2296
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/3272e435220407.56eeae44e2b06.jpg",
            "width": 3680,
            "height": 1840
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/ed3ec135220407.56eeae44e32bb.jpg",
            "width": 4592,
            "height": 2296,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/4049f835220407.56eeae44e3938.jpg",
            "width": 3680,
            "height": 1840
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/6402d135220407.58c044d9c917e.jpg",
            "width": 477,
            "height": 323
        }
    ],
  },
  {
    slug: "tea-lezzetl",
    name: "Tea (Lezzetlı)",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/c489c053111919.Y3JvcCwxMTI1LDg4MSwxMzMsMTc4MQ.jpg",
    width: 808,
    height: 632,
    span: "wide",
    featured: true,
    behanceId: 53111919,
    sourceUrl: "https://www.behance.net/gallery/53111919/Tea-%28Lezzetl%29",
    publishedOn: 1495807030,
    description: "This project had been developed: a Company's Logo (Lezzetli) , Product's Logo(Çaycı) , and product packaging.",
    modules: [
        {
            "type": "text",
            "text": "This project had been developed as : a Company's Logo (Lezzetli) , Product's Logo(Çaycı) , and the product packaging Design."
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/3cccc553111919.592830a5c1dcb.jpg",
            "width": 1449,
            "height": 2898,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/95bd2c53111919.592830a5c2547.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "damascene-perfume",
    name: "DAMASCENE (Perfume)",
    service: "logo-design-visual-identity",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/f4f63254481059.Y3JvcCw3MzEsNTcyLDU3LDIyNw.jpg",
    width: 404,
    height: 316,
    span: "splitWide",
    featured: true,
    behanceId: 54481059,
    sourceUrl: "https://www.behance.net/gallery/54481059/DAMASCENE-%28Perfume%29",
    publishedOn: 1499275856,
    description: "this a logo Design of a Perfume that Distributed In Istanbul- Turkey",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/d67afd54481059.595d20a86d555.jpg",
            "width": 850,
            "height": 1074
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/f8d66d54481059.595d20a86e12c.jpg",
            "width": 850,
            "height": 1074
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/df2f3d54481059.595d20a86d9a8.jpg",
            "width": 850,
            "height": 567
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/a5d7c954481059.595d20a86de2f.jpg",
            "width": 850,
            "height": 567
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/64fd2454481059.595d20a86e87c.jpg",
            "width": 850,
            "height": 708
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/98cecb54481059.595d20a86d0c1.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "cips-bey-winner",
    name: "Cips Bey ( Winner )",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/f284cc47560361.Y3JvcCw4MTQsNjM3LDEwMiw4Mg.jpg",
    width: 808,
    height: 632,
    span: "splitNarrow",
    featured: true,
    behanceId: 47560361,
    sourceUrl: "https://www.behance.net/gallery/47560361/Cips-Bey-%28-Winner-%29",
    publishedOn: 1484670137,
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/ea47b947560361.587e42e90c2d5.jpg",
            "width": 1024,
            "height": 2048
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/cd2e5847560361.587e42e90c850.jpg",
            "width": 1024,
            "height": 2048
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/3c325047560361.587e42e90d255.jpg",
            "width": 1024,
            "height": 2048
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/4f4f5547560361.587e42e90d6fb.jpg",
            "width": 1024,
            "height": 2048
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/d8843b47560361.587e42e910ed7.jpg",
            "width": 1024,
            "height": 2048
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/8913ff47560361.587e593789cf4.jpg",
            "width": 1024,
            "height": 2048
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/56a0d547560361.587e459220880.jpg",
            "width": 430,
            "height": 248
        }
    ],
  },
  {
    slug: "hamsa-corn-chips",
    name: "HAMSA (Corn Chips)",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/30e65249791631.Y3JvcCw4NTIsNjY2LDAsODY2.jpg",
    width: 808,
    height: 632,
    span: "half",
    featured: true,
    behanceId: 49791631,
    sourceUrl: "https://www.behance.net/gallery/49791631/HAMSA-%28Corn-Chips%29",
    publishedOn: 1488901234,
    description: "\"HAMSA\" is a Corn Chips Product Distributed In Turkey.",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/c2b50449791631.596f6f1c386b9.jpg",
            "width": 850,
            "height": 1700
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/6e1b7e49791631.58c0453d9de99.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "hamsa-corn-chips-54480881",
    name: "HAMSA ( Corn Chips )",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/11e4bc54480881.Y3JvcCw4NTMsNjY3LDAsMTQx.jpg",
    width: 808,
    height: 632,
    span: "band",
    featured: true,
    behanceId: 54480881,
    sourceUrl: "https://www.behance.net/gallery/54480881/HAMSA-%28-Corn-Chips-%29",
    publishedOn: 1499275112,
    description: "\"HAMSA\" is a Corn Chips Product Distributed In Turkey.\nThis project had been developed as : Product's Logo (HAMSA) , and the product packaging Design",
    modules: [
        {
            "type": "text",
            "text": "\"HAMSA\" is a Corn Chips Product Distributed In Turkey.\nThis project had been developed as : Product's Logo (HAMSA) , and the product packaging Design.",
            "align": "center"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/fd7d8054480881.595d1f6770497.jpg",
            "width": 851,
            "height": 952
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/83dc5b54480881.595d1f6774533.jpg",
            "width": 851,
            "height": 600
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/468fb954480881.595d2f63c61a7.jpg",
            "width": 851,
            "height": 987
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/4e155554480881.595d1f676fb1c.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "al-kafeel-chips",
    name: "Al Kafeel ( Chips )",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/ca899254478763.Y3JvcCw0NjYsMzY0LDIwMSwzOTA.jpg",
    width: 404,
    height: 316,
    span: "hero",
    featured: false,
    behanceId: 54478763,
    sourceUrl: "https://www.behance.net/gallery/54478763/Al-Kafeel-%28-Chips-%29",
    publishedOn: 1499273730,
    description: "We Designed a package for Potato and Corn Chips, We've been inspired from the shape of each Product .",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/3a459d54478763.595d0f4483aec.jpg",
            "width": 850,
            "height": 1315
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/c7247254478763.595d0f4483371.jpg",
            "width": 850,
            "height": 706
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/60a28454478763.595d0f4482e4e.jpg",
            "width": 850,
            "height": 1315
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/facfa954478763.595d0f448c05f.jpg",
            "width": 850,
            "height": 570
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/32446754478763.595d0f448bca7.jpg",
            "width": 850,
            "height": 1315
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/5a4e1f54478763.595d0f44842d3.jpg",
            "width": 850,
            "height": 567
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/a6ea2d54478763.595d0f4483df3.jpg",
            "width": 850,
            "height": 564
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/27f7bc54478763.595d0f4484679.jpg",
            "width": 850,
            "height": 1315
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/003cd054478763.595d0f4483721.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "orbak-bakliyat-legumes",
    name: "Orbak Bakliyat (Legumes)",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/8eb73254437769.Y3JvcCw1MDksMzk4LDM0MCwyMTM.jpg",
    width: 404,
    height: 316,
    span: "landscape",
    featured: false,
    behanceId: 54437769,
    sourceUrl: "https://www.behance.net/gallery/54437769/Orbak-Bakliyat-%28Legumes%29",
    publishedOn: 1499270666,
    description: "this Project was designed for Orbak Food a company based in Turkey.\nour mission was to Design a general package for their Products ( Lugems )\nWe photographed the main Products that they sell with a NIKON D7000.",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/71dbf654437769.595d0a85c30ac.jpg",
            "width": 850,
            "height": 850
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/809bdd54437769.595d0a85c36b0.jpg",
            "width": 850,
            "height": 1432
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b6156154437769.595d0a85c2cc1.jpg",
            "width": 850,
            "height": 562
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/f0565054437769.595d0a85c28ee.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "behance-syria-gaziantep-15-may-2016",
    name: "Behance Syria - Gaziantep 15 May 2016",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/53098d37135873.Y3JvcCwxMzU5LDEwNjEsMCwyODM.jpg",
    width: 808,
    height: 632,
    span: "landscape",
    featured: false,
    behanceId: 37135873,
    sourceUrl: "https://www.behance.net/gallery/37135873/Behance-Syria-Gaziantep-15-May-2016",
    publishedOn: 1463130847,
    description: "A PROJECT FOR BEHANCE SYRIA IN GAZIANTEP 2016",
    modules: [
        {
            "type": "text",
            "text": "CHARACTERS & GRAPHIC DESIGN شخصيات + تصميم جرافيك",
            "align": "center"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/fb1c5f37135873.57359865029c5.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "text",
            "text": "PRODUCTS PHOTOGRAPHY & GRAPHIC DESIGN تصوير منتجات + تصميم جرافيك",
            "align": "center"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/1e1de837135873.5735986505649.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/4a1b7f37135873.5735986504c61.jpg",
            "width": 866,
            "height": 1435
        },
        {
            "type": "text",
            "text": "LOGOS شعارات",
            "align": "center"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/115eca37135873.573598650354a.jpg",
            "width": 853,
            "height": 1706
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/fc486b37135873.5735986505208.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/e6d0ee37135873.57359865068b6.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "text",
            "text": "DRAWN CHARACTERS شخصيات مرسومة",
            "align": "center"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/fca15637135873.5735986505bf1.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/c530c537135873.5735986502e9e.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "text",
            "text": "POSTERS بوسترات",
            "align": "center"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/7c1fcd37135873.5735986503b96.jpg",
            "width": 866,
            "height": 1224
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/1650f537135873.57359865040d2.jpg",
            "width": 866,
            "height": 826
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/80573537135873.5735986504793.jpg",
            "width": 866,
            "height": 586
        },
        {
            "type": "text",
            "text": "PHOTOGRAPHY تصوير",
            "align": "center"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/199c4137135873.573598650624d.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/7be9a237135873.587e48a1cab60.jpg",
            "width": 430,
            "height": 248
        }
    ],
  },
  {
    slug: "logo-collection-2016",
    name: "Logo Collection 2016",
    service: "logo-design-visual-identity",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/11c67037236871.Y3JvcCwxMzU5LDEwNjEsMCwyOTc.jpg",
    width: 808,
    height: 632,
    span: "third",
    featured: false,
    behanceId: 37236871,
    sourceUrl: "https://www.behance.net/gallery/37236871/Logo-Collection-2016",
    publishedOn: 1463409060,
    description: "The logo collection 2016",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/28312e37236871.5739d803d914a.jpg",
            "width": 853,
            "height": 1706
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b386cc37236871.587e490a88698.jpg",
            "width": 430,
            "height": 248
        }
    ],
  },
  {
    slug: "mr-almond",
    name: "Mr. Almond",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/5b93c937237385.Y3JvcCw0MDQsMzE2LDAsMzQ.jpg",
    width: 404,
    height: 316,
    span: "third",
    featured: false,
    behanceId: 37237385,
    sourceUrl: "https://www.behance.net/gallery/37237385/Mr-Almond",
    publishedOn: 1463409466,
    description: "Mr. Almond",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/97c8b237237385.5739db38877e3.jpg",
            "width": 866,
            "height": 1732
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/8d33b137237385.587e4a7f02f3d.jpg",
            "width": 430,
            "height": 248
        }
    ],
  },
  {
    slug: "froma",
    name: "Froma",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/e5288137235963.Y3JvcCw0MDQsMzE2LDAsNDQ.jpg",
    width: 404,
    height: 316,
    span: "third",
    featured: false,
    behanceId: 37235963,
    sourceUrl: "https://www.behance.net/gallery/37235963/Froma",
    publishedOn: 1463407573,
    description: "Posters",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/58af3437235963.5739d28ff1b20.jpg",
            "width": 394,
            "height": 787
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/fc5dd637235963.5739d28ff1f2f.jpg",
            "width": 394,
            "height": 787
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/0bacdf37235963.587e4ad7d394d.jpg",
            "width": 430,
            "height": 248
        }
    ],
  },
  {
    slug: "seedo-s-bakery",
    name: "Seedo's Bakery",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/001e0937236317.Y3JvcCw0MDQsMzE2LDIxLDE5.jpg",
    width: 404,
    height: 316,
    span: "tall",
    featured: false,
    behanceId: 37236317,
    sourceUrl: "https://www.behance.net/gallery/37236317/Seedos-Bakery",
    publishedOn: 1463408124,
    description: "Bread Packging",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/ec1c3937236317.5739d4d296818.jpg",
            "width": 866,
            "height": 1435
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/e5a2d237236317.587e4aa54ab27.jpg",
            "width": 430,
            "height": 248
        }
    ],
  },
  {
    slug: "baby-castle-kids-wear",
    name: "Baby Castle (kids wear)",
    service: "logo-design-visual-identity",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/96293d35088569.Y3JvcCwxNTgxLDEyMzUsMTA3LDA.jpg",
    width: 808,
    height: 632,
    span: "wide",
    featured: false,
    behanceId: 35088569,
    sourceUrl: "https://www.behance.net/gallery/35088569/Baby-Castle-%28kids-wear%29",
    publishedOn: 1458124745,
    description: "renew the logo of a professenal Brand of kid's wear.",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/2d2c1035088569.56e937c7ddda2.jpg",
            "width": 853,
            "height": 1706
        }
    ],
  },
  {
    slug: "traffic-christmas-tree",
    name: "Traffic Christmas Tree",
    service: "graphic-design-packaging-design",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/1cab9f49138045.Y3JvcCwxMjc3LDEwMDAsNTksMA.jpg",
    width: 808,
    height: 632,
    span: "splitWide",
    featured: false,
    behanceId: 49138045,
    sourceUrl: "https://www.behance.net/gallery/49138045/Traffic-Christmas-Tree",
    publishedOn: 1487757489,
    description: "We tried in this work to merge the Main logo of the restaurant with the concept of\n \" New Year \" Through the Christmas Tree.\nAnd as you can see that the Key element of the logo is the traffic lights so We came up with the idea of traffic Christmas tree.",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/86a74149138045.58ac3e70c4645.jpg",
            "width": 4730,
            "height": 3524,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/c7a18849138045.58ad5d886b30d.jpg",
            "width": 4783,
            "height": 2392,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/3f3ea849138045.58ad5d888ec24.jpg",
            "width": 4783,
            "height": 3826,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/61228449138045.58ad5d886ae2b.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "logo-collection-the-year-of-2010",
    name: "Logo Collection the year of 2010",
    service: "logo-design-visual-identity",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/26daac32358679.Y3JvcCwxMzU5LDEwNjEsMCwyOTc.jpg",
    width: 808,
    height: 632,
    span: "splitNarrow",
    featured: false,
    behanceId: 32358679,
    sourceUrl: "https://www.behance.net/gallery/32358679/Logo-Collection-the-year-of-2010",
    publishedOn: 1451033948,
    description: "Logo Collection 2010",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/172e7832358679.567d055b10a52.jpg",
            "width": 1280,
            "height": 2560
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/09f0ad32358679.587e55e762b9a.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "suter-international",
    name: "Suter international",
    service: "logo-design-visual-identity",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/8ad80932025447.Y3JvcCw3OTMsNjE5LDEyMSw0OA.jpg",
    width: 404,
    height: 316,
    span: "half",
    featured: false,
    behanceId: 32025447,
    sourceUrl: "https://www.behance.net/gallery/32025447/Suter-international",
    publishedOn: 1449853503,
    description: "Company Logo...",
    modules: [
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/5eb5cf32025447.566aff80af5d2.jpg",
            "width": 1024,
            "height": 2048
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/91c43b32025447.587e51b636192.png",
            "width": 439,
            "height": 251
        }
    ],
  },
  {
    slug: "sakk-ovens-company",
    name: "Sakk Ovens Company",
    service: "logo-design-visual-identity",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/original/5dc76332329085.Y3JvcCw0ODcsMzgxLDAsNjc.jpg",
    width: 404,
    height: 316,
    span: "band",
    featured: false,
    behanceId: 32329085,
    sourceUrl: "https://www.behance.net/gallery/32329085/Sakk-Ovens-Company",
    publishedOn: 1450885107,
    description: "SAKK Ovens for Bread Production line",
    modules: [
        {
            "type": "text",
            "text": "this project is a renewal of the Identity of an Industrial Company Based In Turkey."
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/527b2732329085.5929739e86489.jpg",
            "width": 3252,
            "height": 1626,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/149c5332329085.592975b519c62.jpg",
            "width": 3250,
            "height": 1625,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/27d9dc32329085.592975b51a414.jpg",
            "width": 3250,
            "height": 1625,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/4a05b732329085.592975b519f2a.jpg",
            "width": 3250,
            "height": 2400,
            "fullBleed": true
        },
        {
            "type": "youtube",
            "id": "hFuN4zGYwgY"
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/e1262d32329085.5929817b737e3.jpg",
            "width": 3250,
            "height": 1901,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/b6d1ac32329085.5929817b731e9.jpg",
            "width": 3250,
            "height": 1625,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/9a9e8832329085.592975b51974f.jpg",
            "width": 3250,
            "height": 1625,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/65da8332329085.5929817b72e40.jpg",
            "width": 3250,
            "height": 1625,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/35de1c32329085.5929817b73cf7.jpg",
            "width": 3250,
            "height": 1625,
            "fullBleed": true
        },
        {
            "type": "image",
            "src": "https://mir-s3-cdn-cf.behance.net/project_modules/source/08cda332329085.59298352b74be.jpg",
            "width": 3250,
            "height": 1625,
            "fullBleed": true
        }
    ],
  }
]

export type ProjectSlug = (typeof projects)[number]['slug']
